### ISSUE TITLE
HP In Title Bar Doesn't Update From Other Sources

### ISSUE THREAD

**Issue by gfactor** [ironmonk88/always-hp#8]
When selecting a token, the title bar of the Always HP bar shows the current HP of that actor and updates the HP in real-time when changes are made using the Always HP bar. However, if changes are made to that actor's HP outside the Always HP bar (such as from buttons on dice rolls in chat), the Always HP title bar doesn't show those changes until you deselect and reselect that token.

Example using the following versions/modules:
Founder VTT 0.7.9
Pathfinder 2nd Edition 1.11.1.3306
Always HP 1.0.17

1. Create a new game world using the Pathfinder 2nd Edition game system.
2. Launch this new world and sign in as the Gamemaster.
3. Activate the Always HP module.
3. Create a new scene. (The name and options don't matter, we just need a place to drop a token.)
4. Create a new Non-Player Character actor. (The name and options don't matter as long as they have some HP. By default, new NPC actors start with 10 HP.)
5. Drag the actor to the map so a token is created, then click the token so it's selected and the Always HP bar title bar shows the token name and HP.
6. In the Chat Log, roll any kind of dice that can be interpreted as damage dice (such as /r d6).
7. In the message that popped up, click the button to apply full damage to the selected token. Notice that even though a chat message has appeared about an actor taking damage and the token's HP bar has decreased, the Always HP title bar still shows full HP.
8. Deselect the token, then reselect it. Notice that the Always HP title bar now shows the correct HP for that actor.

In my group, my players and I use both the buttons in chat and the Always HP bar to manipulate HP on actors. (For example, currently in the PF2E module, damage typing hasn't been connected to resistances. So if a player with a resistance of fire 5 takes fire damage, they'll click the chat button to take full damage, then give themselves 5 HP of healing through Always HP to represent their resistance.) I realize this may not be a common scenario for GMs since they're always switching tokens. But for my players, this is a constant annoyance to have to deselect and reselect their character every time they manipulate their HP.

**Comment by ironmonk88** [comment]
That's really weird, I swear I added the code for 1.0.18.  
Fixed it with 1.0.19.
Really appreciate the detailed bug report.  That was amazing.

**Comment by gfactor** [comment]
I retested this with Always HP 1.0.19 (and the same Foundry and PF2E version) and I'm still getting the same result: the Always HP title bar isn't showing the correct HP when it's changed via the chat message button. It's possible something might be cached or messed up on my side. Do you know if there's anything I can check to make sure I have the latest module version and it's working as expected?
